export type LogoCatalog =
  | 'MacroTagLine'
  | 'Agro'
  | 'BankLimited'
  | 'BankLimitedVertical'
  | 'ClickDePago'
  | 'Fiducia'
  | 'Fondos'
  | 'Iso'
  | 'MacroHorizontal'
  | 'MacroTagLine'
  | 'MacroVertical'
  | 'Premia'
  | 'Securities'
  | 'SelectaPrivado'
  | 'Selecta'
  | 'Wink'
  | undefined
