/* eslint-disable @typescript-eslint/consistent-type-exports */
import { getAsset } from './functions/getAsset'
import {
  Agro,
  BankLimited,
  BankLimitedVertical,
  ClickDePago,
  Fiducia,
  Fondos,
  Iso,
  MacroHorizontal,
  MacroTagLine,
  MacroVertical,
  Premia,
  Securities,
  SelectaPrivado,
  Selecta,
  Wink
} from './logos'
import {
  Alert,
  Bag,
  Calendar,
  Car,
  Card,
  CardSmile,
  Cart,
  Cash,
  Clock,
  Doc,
  Home,
  Laptop,
  Location,
  Lock,
  Message,
  Microphone,
  Plus,
  Question,
  Smartphone,
  Trash,
  User,
  Validation
} from './pictograms'
import { HandTeamMacro, Hand } from './illustrations'
import type { IllustrationCatalog } from './types/illustrationTypes'
import type { LogoCatalog } from './types/logoTypes'
import type { PictogramCatalog } from './types/pictogramTypes'
export {
  getAsset,
  LogoCatalog,
  Agro,
  BankLimited,
  BankLimitedVertical,
  ClickDePago,
  Fiducia,
  Fondos,
  HandTeamMacro,
  Hand,
  Iso,
  MacroHorizontal,
  MacroTagLine,
  MacroVertical,
  Premia,
  Securities,
  SelectaPrivado,
  Selecta,
  Wink,
  PictogramCatalog,
  Alert,
  Bag,
  Calendar,
  Car,
  CardSmile,
  Card,
  Cart,
  Cash,
  Clock,
  Doc,
  Home,
  Laptop,
  Location,
  Lock,
  Message,
  Microphone,
  Plus,
  Question,
  Smartphone,
  Trash,
  User,
  Validation,
  IllustrationCatalog
}
